UMU = '../exe/umu'

FILES =	[
    'test.umu',
    'list.umu',
    'set.umu',
    'database/database-systems.umu',
    'database/database-systems-jp.umu',
    'sicp/sicp-ch1.umu',
    'sicp/sicp-ch2.umu',
    'sicp/sicp-ch3.umu',
    'delayed-evaluation/1-tarai.umu',
    'delayed-evaluation/2-sum-ints.umu',
    'delayed-evaluation/3-primes.umu'
]



task :default => :help


task :help do
	puts "[Making Rules]"
	puts "    run : Run all scripts"
	puts "  files : List script files"
	puts
end


task :run => FILES do
    FILES.each do |file|
        puts "==== #{file} ===="
        sh "#{UMU} #{file}"
        puts
        puts
    end
    sh 'rake -C definitional-interpreter/ test'
end


task :files do
    FILES.each do |file|
        puts file
    end
    sh "rake -C definitional-interpreter/ files | " +
            "awk '{ printf(\"definitional-interpreter/%s\\n\", $0) }'"
end
