UMU = '../exe/umu'

FILES =	[
    'test.umu',
    'list.umu',
    'set.umu',
    'definional-interpreter.umu',
    'database/database-systems.umu',
    'database/database-systems-jp.umu',
    'sicp/sicp-ch1.umu',
    'sicp/sicp-ch2.umu',
    'sicp/sicp-ch3.umu'
]



task :default => :help


task :help do
	puts "[Making Rules]"
	puts "    run : Run all scripts"
	puts "  files : List script files"
	puts
end


task :run => FILES do
    FILES.each do |file|
        puts "==== #{file} ===="
        sh "#{UMU} #{file}"
        puts
        puts
    end
end


task :files do
    FILES.each do |file|
        puts file
    end
end
