require 'umu/concrete-syntax/core/declaration/abstract'
require 'umu/concrete-syntax/core/declaration/assert'
require 'umu/concrete-syntax/core/declaration/value'
require 'umu/concrete-syntax/core/declaration/function'
require 'umu/concrete-syntax/core/declaration/recursive'
