require_relative 'declaration/abstract'
require_relative 'declaration/assert'
require_relative 'declaration/value'
require_relative 'declaration/function'
require_relative 'declaration/recursive'
require_relative 'declaration/seq-of-declaration'
