require 'umu/abstract-syntax/core/expression/unary/base/abstract'
require 'umu/abstract-syntax/core/expression/unary/base/bool'
require 'umu/abstract-syntax/core/expression/unary/base/number'
require 'umu/abstract-syntax/core/expression/unary/base/string'
require 'umu/abstract-syntax/core/expression/unary/base/atom'
