require_relative 'container/abstraction'
require_relative 'container/tuple'
require_relative 'container/named-tuple'
require_relative 'container/struct'
require_relative 'container/list'
require_relative 'container/stream'
