require_relative 'common/constant'
require_relative 'common/assertion'
require_relative 'common/exception'
require_relative 'common/abstraction'
require_relative 'common/escape'
require_relative 'common/location'
require_relative 'common/pretty-print'
