require_relative 'unary/abstract'
require_relative 'unary/atom'
require_relative 'unary/prefix.rb'
require_relative 'unary/identifier'
require_relative 'unary/class'
require_relative 'unary/method'
require_relative 'unary/container'
