require_relative 'declaration/abstract'
require_relative 'declaration/simple'
require_relative 'declaration/mutual-recursive'
require_relative 'declaration/import'
require_relative 'declaration/declarations'
